
services:
  # Servicio del frontend (Angular)
  frontend:
    build:
      context:  .    # El contexto de construcción está en la carpeta 'frontend'
      dockerfile: Dockerfile       # Dockerfile que has creado para la construcción
    ports:
      - "80:80"                    # Exponer el puerto 80 para acceso a la aplicación Angular
    networks:
      - kong-net                  # Puedes añadirlo a la red si es necesario para interactuar con otros servicios

  # Base de datos para Kong
  kong-database:
    image: postgres:15
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - kong-net
    volumes:
      - kong-db-data:/var/lib/postgresql/data

  # Kong Gateway
  kong:
    image: kong:3.5
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-database
    ports:
      - "8000:8000" # Puerto para las solicitudes proxy
      - "8001:8001" # Puerto para el administrador de Kong
    networks:
      - kong-net

networks:
  kong-net:

volumes:
  kong-db-data:
